### ISSUE TITLE
cvcnet_train 

### ISSUE THREAD

**Issue by chenjiachengzzz** [xyzhu1/CVCnet#1]
<img width="500" alt="1646840272(1)" src="https://user-images.githubusercontent.com/54382260/157475380-25c6f0f2-8893-457e-a1b1-9a9b23cf07f3.png">
您好，measure函数没有申明！

**Comment by xyzhu1** [comment]
Thanks for your attention
in the cvcnet_train.py, we have: from utils import *
in the utils.py, we have: from skimage import measure,metrics 
Please check if skimage is installed

**Comment by chenjiachengzzz** [comment]
> 
thanks
